# Generated by Django 5.2.17 on 2026-10-01 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='is_dismissed',
            field=models.BooleanField(default=False),
        ),
    ]
